source 'https://github.com/CocoaPods/Specs.git'

target 'HUMAudioRecorder_Example', :exclusive => true do
  pod "HUMAudioRecorder", :path => "../"
end

target 'HUMAudioRecorder_Tests', :exclusive => true do
  pod "HUMAudioRecorder", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
