source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HUMAudioRecorder_Example' do
  pod "HUMAudioRecorder", :path => "../"
  
  target 'HUMAudioRecorder_Tests' do
      inherit! :search_paths
      pod 'Specta'
      pod 'Expecta'
  end
end
